<a href="https://colab.research.google.com/github/Prabandari0607/SC-Lab-Prabandari/blob/main/SC_sesi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("Hello World")

Hello World


In [ ]:
import time

In [ ]:
print(time.ctime())

Thu Feb  6 04:41:10 2025


In [ ]:
z = "Hello"
y = 4
x = 3.9
f = ["Apple", "Berry"]
x, y, z, f

(3.9, 4, 'Hello', ['Apple', 'Berry'])

In [ ]:
o = int(1)
y = int(2.8)
z = int("3") #type casting
j = str(20)

o,y,z,j

print (o, y, z, j)

1 2 3 20


type casting, digunakan untuk mengubah suatu tipe data

In [ ]:
a = "Hello World "
b = "Good Morning"
c = a+b

print(c)


Hello World Good Morning


In [ ]:
a ="Hello World"

print(a[3])

print(len(a))

l
11


In [ ]:
b = "BINUS univ"
print(b[2:5])

c = "BINUS univ"
print(c[:5])

d = "BINUS univ"
print(d[2:])

NUS
BINUS
NUS univ


In [ ]:
a = "Hello"
print(a.upper())

b = "Hello"
print(b.lower())
a = "Hello"
print(a.upper())

b = "Hello"
print(b.lower())

c = "Hello"
print(c.replace("H", "J"))

HELLO
hello
HELLO
hello
Jello


In [ ]:
nama = "sam"
x = 19
string = "nama saya {} , umurku {}"

print(string.format(nama,x))

nama saya sam , umurku 19


In [ ]:
nama = "grace"
for i in enumerate(nama):
  print(i)

(0, 'g')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [ ]:
def perbandingan (a,b):
  if a>b:
    print("a lebih dari b")
  elif a<b:
    print("a kurang dari b")
  else:
    print("a = b")

In [ ]:
perbandingan(67,87)

a kurang dari b


In [ ]:
i=1
while i<6:
  print(i)

  i+=1

1
2
3
4
5


In [ ]:
i=3
for i in range(2,6):
  print(i)

2
3
4
5


In [ ]:
for i in range(2,41):
  if i % 2==0:
     print(i, "genap")
  else:
    print(i, "ganjil")


2 genap
3 ganjil
4 genap
5 ganjil
6 genap
7 ganjil
8 genap
9 ganjil
10 genap
11 ganjil
12 genap
13 ganjil
14 genap
15 ganjil
16 genap
17 ganjil
18 genap
19 ganjil
20 genap
21 ganjil
22 genap
23 ganjil
24 genap
25 ganjil
26 genap
27 ganjil
28 genap
29 ganjil
30 genap
31 ganjil
32 genap
33 ganjil
34 genap
35 ganjil
36 genap
37 ganjil
38 genap
39 ganjil
40 genap


In [ ]:
import numpy as np

In [ ]:
x = np.array([[1, 2, 3], [6,7,8]])
x

array([[1, 2, 3],
       [6, 7, 8]])

In [ ]:
y = np.array([[4, 2, 5], [6,9,8]])
y

array([[4, 2, 5],
       [6, 9, 8]])

In [ ]:
print(x+y)

[[ 5  4  8]
 [12 16 16]]


In [ ]:
data = np.array([10, 8, 5, 7, 6])
print("Rata-rata:", np.mean(data))
print("Maksimum:", np.max(data))
print("Minimum:", np.min(data))
print("Standar devisiasi:", np.std(data))

Rata-rata: 7.2
Maksimum: 10
Minimum: 5
Standar devisiasi: 1.7204650534085253


In [ ]:
username = input("Masukkan username anda: ")
password_benar = "Admin123"

while True:
 password = input("Masukkan password anda: ")
 if password == password_benar:
  print(f"Login berhasil, Selamat datang {username}")
  break
 else
  print("Tolong masukkan data yang valid")

nama = input("Masukkan nama siswa:")
UAS = int(input("Masukkan nilai UAS: "))
UTS = int(input("Masukkan nilai UTS: "))
Assignment = int(input("Masukkan nilai Assignment: "))
grades =(UAS*0.5) + (UTS*0.3) + (Assignment*0.2)

print("\ngranding system")
print("---------------------")
string = "hasil perolehan nilai {}"
print(string.format(nama))
string = "Final scores: {}"
print(string.format(grades))

if 90<= grades <=100:
  final = 'A'
elif 85<= grades <=89:
  final = 'A-'
elif 80<= grades <=84:
  final = 'B+'
elif 75<= grades <=79:
  final = 'B'
elif 70<= grades <=74:
  final = 'B-'
elif 65<= grades <=69:
  final = 'C'
elif 60<= grades <=64:
  final = 'D'
elif 11<= grades <=59:
  final = 'E'
else:
  final = 'F'
string = "Grade {}"
print(string.format(final))



Masukkan username anda: tya0607
Masukkan password anda: araya123
Tolong masukkan data yang valid
Masukkan password anda: Admin123
Login berhasil, Selamat tya0607
Masukkan nama siswa:yasin
Masukkan nilai UAS: 100
Masukkan nilai UTS: 90
Masukkan nilai Assignment: 89

granding system
---------------------
hasil perolehan nilai yasin
Final scores: 94.8
Grade A
